import { useSite } from '../content/SiteContent';
import { useEffect, useState, type CSSProperties } from 'react';
import tokens from './tokens.json';
import typography from './typography.json';
import LocaleTypography from './LocaleTypography';
import { Button, ButtonLink, Input, Textarea, Card, Badge, Stack, Container, Accordion, Dialog, Tabs } from './components';
import { Navigation } from '../components/Navigation';
import './gallery.css';

type DesignSystemProps={embedded?:boolean;tokenOverrides?:Record<string,string>;onEditTokens?:()=>void};
export default function DesignSystem({embedded=false,tokenOverrides,onEditTokens}:DesignSystemProps){
  const {site}=useSite();
  const overrides=tokenOverrides??site.tokenOverrides;
  const effective=(group:string,name:string,value:string)=>overrides[`--${group}-${name}`]??value;
  const savedBrand=effective('color','brand',tokens.color.brand.value);
  const [brand,setBrand]=useState(tokens.color.brand.value),[tab,setTab]=useState('services'),[open,setOpen]=useState(false),[loading,setLoading]=useState(false);
  useEffect(()=>{setBrand(savedBrand);},[savedBrand]);
  const previewingBrand=brand!==savedBrand;
  const Root=embedded?'div':'main';
  const Heading=embedded?'h2':'h1';
  return <>{!embedded&&<Navigation/>}<Root id={embedded?undefined:'page-main'} className={`ds-gallery${embedded?' ds-gallery--embedded':''}`} dir="ltr" style={{...overrides,'--color-brand':brand,...(previewingBrand?{'--color-focus':brand}:{})} as CSSProperties}><Container>
    <div className="ds-gallery-hero"><Badge>Bextudio / v1.0</Badge><Heading>{embedded?'Component library':'Design system'}</Heading><p>The foundation for every Bextudio interface. Explore the shared colors, typography and reusable components.</p><div className="ds-gallery-toolbar"><label>Preview brand color <input type="color" aria-label="Preview brand color" value={/^#[0-9a-f]{6}$/i.test(brand)?brand:tokens.color.brand.value} onChange={e=>setBrand(e.target.value)}/></label><Button variant="secondary" onClick={()=>setBrand(savedBrand)}>Reset preview</Button>{onEditTokens?<Button onClick={onEditTokens}>Edit design tokens</Button>:<ButtonLink href="/admin?section=design-system&view=tokens">Manage in admin</ButtonLink>}</div><small>{embedded?'This library reflects your draft tokens. The color picker is a temporary preview; use Design tokens and Save changes to update the website.':'The color picker is a temporary preview. Manage shared styles in Admin → Design system → Design tokens.'}</small></div>
    <nav className="ds-section-nav" aria-label="Design system sections">{['Colors','Typography','Spacing','Buttons','Forms','Cards','Patterns','Guidelines'].map(name=><a href={'#ds-'+name.toLowerCase()} key={name}>{name}</a>)}</nav>
    <section id="ds-colors"><h2>Colors</h2><p>Existing brand palette plus semantic colors for component states.</p><div className="ds-swatch-grid">{Object.entries(tokens.color).map(([name,token])=><div className="ds-swatch" key={name}><div style={{background:`var(--color-${name})`}}/><strong>{name}</strong><code>{name==='brand'||(name==='focus'&&previewingBrand)?brand:effective('color',name,token.value)}</code><small>--color-{name}</small></div>)}</div></section>
    <section id="ds-typography"><h2>Typography</h2><p>Local Inter, Estedad and IBM Plex Sans Arabic fonts. Desktop, tablet and mobile text roles; the migrated pages keep any original per-section size overrides.</p><div className="ds-type-list">{Object.entries(typography).map(([name,type])=><div className="ds-type-row" key={name}><div><strong>{name}</strong><code>{type.desktop} / {type.tablet} / {type.mobile} px · {type.weight} · {type.lineHeight}</code></div><p style={{fontSize:`clamp(${type.mobile}px, 4vw, ${type.desktop}px)`,fontWeight:type.weight,lineHeight:type.lineHeight,letterSpacing:type.tracking}}>Build an intelligent brand.</p></div>)}</div><LocaleTypography overrides={overrides}/></section>
    <section id="ds-spacing"><h2>Spacing and shape</h2><div className="ds-space-list">{[4,8,12,16,24,32,48,64,96].map(n=><div key={n}><code>--space-{n}</code><span style={{width:`var(--space-${n})`}}/><small>{effective('space',String(n),n+'px')}</small></div>)}</div><div className="ds-radius-list">{Object.entries(tokens.radius).map(([name,token])=><div key={name} style={{borderRadius:`var(--radius-${name})`}}>{name}<small>{effective('radius',name,token.value)}</small></div>)}</div></section>
    <section id="ds-buttons"><h2>Buttons and states</h2><Stack direction="row" className="ds-wrap"><Button>Primary action</Button><Button variant="secondary">Secondary</Button><Button variant="ghost">Text action</Button><Button variant="danger">Destructive</Button><Button disabled>Disabled</Button><Button loading={loading} onClick={()=>setLoading(!loading)}>{loading?'Working…':'Preview loading'}</Button>{loading&&<Button variant="ghost" onClick={()=>setLoading(false)}>Stop preview</Button>}</Stack><Stack direction="row" className="ds-wrap"><Button size="sm">Small</Button><Button>Medium</Button><Button size="lg">Large</Button><ButtonLink href="/contact">Link action ↗</ButtonLink></Stack></section>
    <section id="ds-forms"><h2>Form fields</h2><div className="ds-demo-grid"><Stack><Input label="Email address" type="email" placeholder="you@company.com" hint="We use a visible label, even with a placeholder." required/><Input label="Error state" defaultValue="invalid-email" error="Enter a valid email address."/><Input label="Disabled state" value="Unavailable" disabled readOnly/></Stack><Textarea label="Project brief" placeholder="Tell us about your brand…" hint="This is a component preview; nothing is submitted."/></div></section>
    <section id="ds-cards"><h2>Cards and badges</h2><div className="ds-demo-grid"><Card><Badge>AI Agent</Badge><h3>Image Generator</h3><p>Generate Accurate Images Rapidly</p><ButtonLink href="/agents/image-generator">Try it now</ButtonLink></Card><Card tone="muted"><Badge tone="neutral">Brand strategy</Badge><h3>A shared foundation</h3><p>Compose content using common spacing, text roles and actions.</p><Button variant="secondary" onClick={()=>setOpen(true)}>Open dialog</Button></Card></div><Stack direction="row" className="ds-wrap"><Badge>Brand</Badge><Badge tone="neutral">Neutral</Badge><Badge tone="success">Success</Badge><Badge tone="warning">Warning</Badge><Badge tone="danger">Error</Badge></Stack></section>
    <section id="ds-patterns"><h2>Interactive patterns</h2><Tabs items={[{id:'services',label:'Services'},{id:'agents',label:'Agents'},{id:'factory',label:'Content factory'}]} value={tab} onChange={setTab}/><div role="tabpanel" className="ds-tab-panel"><h3>{tab==='services'?'Expert services':tab==='agents'?'Specialized agents':'Content factory'}</h3><p>Use the arrow keys to navigate tabs. This panel demonstrates selected state.</p></div><Accordion title="How do we change the brand color?"><p>Open Design tokens, edit --color-brand, preview it in the component library, then Save changes. Reset returns a token to its original value.</p></Accordion><Accordion title="How do we redesign one section?"><p>Use components.tsx for new sections. Page-specific layouts stay in src/pages and src/styles; local data and assets stay in src/content and public/assets.</p></Accordion></section>
    <section id="ds-guidelines"><h2>Usage guidelines</h2><div className="ds-demo-grid"><Card><h3>Build with intent</h3><p>One primary action per decision. Use semantic HTML, visible field labels, clear loading and error states, and real content.</p><p>Use the 8px spacing rhythm; 4px is available for tight internal alignment. Mobile stacks below 810px; full desktop starts at 1440px.</p></Card><Card><h3>Preserve accessibility</h3><p>Keyboard focus stays visible. Controls have at least a 44px target. Dialogs trap focus through the native browser dialog. Motion respects reduced motion.</p><p>When changing colors, check text contrast again. Original brand colors are retained; colored status text has separate semantic tokens.</p></Card></div><p className="ds-gallery-footer">Documentation: docs/DESIGN-SYSTEM.md · Source: src/design-system/</p></section>
    </Container><Dialog open={open} onClose={()=>setOpen(false)} title="Reusable dialog"><p>Escape closes this dialog. Focus returns to its trigger.</p><Input label="Example field" placeholder="Type here…"/><div style={{marginTop:24}}><Button onClick={()=>setOpen(false)}>Done</Button></div></Dialog></Root></>;
}
