import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { Button, Input, Textarea, Card, Badge, Tabs } from '../design-system';
import DesignSystem from '../design-system/DesignSystem';
import LocaleTypography from '../design-system/LocaleTypography';
import { postJson } from '../components/Forms';
import { type SiteData, type Article } from '../content/SiteContent';
import assets from '../../docs/asset-manifest.json';
import './admin.css';

type Copy={id:string;route:string;role:string;text:string;label:string};
type Payload={site:SiteData;originals:{translations:Record<string,Record<string,string>>;translationSources:string[];copy:Copy[];tokens:Record<string,Record<string,{value:string}>>;routes:string[]};contacts:{id:number;name:string;email:string;message:string;created_at:string}[];subscribers:{email:string;created_at:string}[];history:{id:number;created_at:string;label:string}[]};
const sections=[['pages','Page content'],['articles','Articles'],['translations','Translations'],['design-system','Design system'],['media','Media library'],['settings','Settings & navigation'],['submissions','Submissions'],['history','Revision history']] as const;
function initialSection(){const requested=new URLSearchParams(location.search).get('section');return requested==='theme'?'design-system':sections.find(([id])=>id===requested)?.[0]??'pages';}
function download(name:string,text:string,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url);}
const csv=(rows:Record<string,unknown>[])=>{const keys=Object.keys(rows[0]??{});return [keys,...rows.map(r=>keys.map(k=>r[k]))].map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n');};

function editorialText(html:string){const dom=new DOMParser().parseFromString(html,'text/html');return Array.from(dom.querySelectorAll('p,h2,h3,h4,li,blockquote')).filter(el=>!el.querySelector('p,li')).map(el=>(el.textContent||'').trim());}
export default function Admin(){
  const [payload,setPayload]=useState<Payload|null>(null),[site,setSite]=useState<SiteData|null>(null),[section,setSection]=useState<string>(initialSection),[designView,setDesignView]=useState(['tokens','typography'].includes(new URLSearchParams(location.search).get('view')??'')?new URLSearchParams(location.search).get('view')!:'library'),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[route,setRoute]=useState('/'),[search,setSearch]=useState(''),[articleId,setArticleId]=useState(''),[mediaTarget,setMediaTarget]=useState(''),[uploaded,setUploaded]=useState(''),[translationLocale,setTranslationLocale]=useState('fa');
  useEffect(()=>{const query=new URLSearchParams();if(section!=='pages')query.set('section',section);if(section==='design-system'&&designView!=='library')query.set('view',designView);history.replaceState(null,'','/admin'+(query.size?'?'+query.toString():''));},[section,designView]);
  async function load(){const response=await fetch('/api/admin/content');if(response.ok){const result=await response.json();setPayload(result);setSite(result.site);setDirty(false);}else{setPayload(null);setSite(null);}}
  useEffect(()=>{void load();},[]);
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
  const update=(fn:(draft:SiteData)=>void)=>{setSite(current=>{if(!current)return current;const next=structuredClone(current);fn(next);return next;});setDirty(true);};
  async function login(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);try{await postJson('/api/admin/login',Object.fromEntries(new FormData(event.currentTarget)));await load();setStatus('');}catch(error){setStatus((error as Error).message);}finally{setBusy(false);}}
  async function save(){if(!site)return;setBusy(true);try{const result=await postJson('/api/admin/save',{site,revision:site.revision});setSite(result.site);setDirty(false);setStatus('Changes saved.');new BroadcastChannel('bextudio-content').postMessage('saved');const response=await fetch('/api/admin/content');if(response.ok)setPayload(await response.json());}catch(error){setStatus((error as Error).message);}finally{setBusy(false);}}
  async function restore(id:number){if(!site)return;setBusy(true);try{await postJson('/api/admin/restore',{id,revision:site.revision});await load();setStatus('Selected revision restored.');new BroadcastChannel('bextudio-content').postMessage('saved');}catch(error){setStatus((error as Error).message);}finally{setBusy(false);}}
  const copy=useMemo(()=>{const seen=new Set<string>();return (payload?.originals.copy??[]).filter(c=>{const key=/^[0-9a-f]{16}$/.test(c.id)?c.route+'|'+c.text:c.id;if(seen.has(key)||c.route.startsWith('/blog/'))return false;seen.add(key);return c.route===route&&(!search||c.text.toLowerCase().includes(search.toLowerCase()));});},[payload,route,search]);
  if(!site||!payload)return <main id="page-main" className="admin-login" dir="ltr"><Card><Badge>Bextudio Admin</Badge><h1>Site administration</h1><p>Initial credentials are stored in the local .env file as ADMIN_EMAIL and ADMIN_PASSWORD.</p><form onSubmit={login}><Input label="Admin email" name="email" type="email" autoComplete="username" defaultValue="admin@bextudio.local" required/><Input label="Password" name="password" type="password" autoComplete="current-password" required/><Button loading={busy} type="submit">Sign in</Button><p role="status">{status}</p></form><a href="/">Back to website</a></Card></main>;
  const selected=site.articles.find(a=>a.id===articleId);
  const editArticle=(key:string,value:unknown)=>update(draft=>{const article=draft.articles.find(a=>a.id===articleId);if(article)Object.assign(article,{[key]:value});});
  const translationSources=Array.from(new Set([...payload.originals.translationSources,...Object.values(site.edits),...site.settings.navigation.map(n=>n.label),site.settings.dashboardLabel,site.settings.footerText,...site.articles.flatMap(a=>[a.title,a.summary,a.readTime,a.seoTitle,a.seoDescription,...editorialText(a.bodyHtml)])])).filter(Boolean).filter(text=>!search||text.toLowerCase().includes(search.toLowerCase()));
  const localImages=assets.filter(a=>/\.(png|jpe?g|webp|gif)$/i.test(a.path));
  return <main id="page-main" className="admin-shell" dir="ltr"><aside className="admin-sidebar"><a className="admin-brand" href="/admin">Bextudio <small>Admin</small></a><nav aria-label="Administration sections">{sections.map(([id,label])=><button key={id} className={section===id?'active':''} aria-current={section===id?'page':undefined} onClick={()=>{setSection(id);setSearch('');}}>{label}</button>)}</nav><a href="/" target="_blank" rel="noreferrer">View website ↗</a><Button variant="ghost" onClick={async()=>{await postJson('/api/auth/logout',{});setSite(null);setPayload(null);}}>Sign out</Button></aside>
  <div className="admin-workspace"><header className="admin-toolbar"><div><h1>{sections.find(s=>s[0]===section)?.[1]}</h1><small>{dirty?'Unsaved changes':`Saved revision: ${site.revision}`}</small></div><div><Button variant="secondary" onClick={()=>download('bextudio-content-backup.json',JSON.stringify(site,null,2))}>Download backup</Button><Button disabled={!dirty} loading={busy} onClick={save}>Save changes</Button></div></header><p className="admin-status" role="status">{status}</p>
  {section==='pages'&&<><div className="admin-controls"><label>Page<select value={route} onChange={e=>setRoute(e.target.value)}>{payload.originals.routes.filter(p=>!p.startsWith('/blog/')&&p!=='/admin').map(p=><option key={p}>{p}</option>)}</select></label><Input label="Search page text" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search for a phrase"/></div><label className="admin-check"><input type="checkbox" checked={!site.hiddenRoutes.includes(route)} onChange={e=>update(d=>{d.hiddenRoutes=e.target.checked?d.hiddenRoutes.filter(p=>p!==route):[...d.hiddenRoutes,route];})} disabled={route==='/design-system'}/>Enable this page</label><p className="admin-help">Original copy remains in the source. Reset removes the saved override. Identical desktop and mobile blocks update together.</p><div className="admin-copy-list">{copy.map(c=><Card key={c.id}><div className="admin-field-heading"><Badge tone="neutral">{c.role}</Badge><Button size="sm" variant="ghost" onClick={()=>update(d=>{for(const duplicate of payload.originals.copy.filter(x=>x.id===c.id||(/^[0-9a-f]{16}$/.test(c.id)&&x.route===c.route&&x.text===c.text)))delete d.edits[duplicate.id];})}>Reset</Button></div><Textarea label={c.label} value={site.edits[c.id]??c.text} onChange={e=>update(d=>{for(const duplicate of payload.originals.copy.filter(x=>x.id===c.id||(/^[0-9a-f]{16}$/.test(c.id)&&x.route===c.route&&x.text===c.text)))d.edits[duplicate.id]=e.target.value;})}/></Card>)}</div>{!copy.length&&<p>This page uses components or structured content. Manage articles in Articles; edit custom component structure in the source.</p>}</>}
  {section==='articles'&&<><div className="admin-controls"><Button onClick={()=>{const id=crypto.randomUUID();update(d=>d.articles.push({id,slug:'new-article-'+Date.now(),title:'New article',summary:'',bodyHtml:'<p>Write your article here.</p>',extraHtml:'',image:localImages[0]?.path||'',date:new Date().toISOString().slice(0,10),author:site.settings.siteName,readTime:'4 min read',featured:false,draft:true,seoTitle:'New article',seoDescription:'',socialImage:''}));setArticleId(id);}}>New article</Button><label>Article<select value={articleId} onChange={e=>setArticleId(e.target.value)}><option value="">Select an article</option>{site.articles.map(a=><option value={a.id} key={a.id}>{a.title}{a.draft?' — Draft':''}</option>)}</select></label></div>{selected&&<Card className="admin-article-editor"><div className="admin-two-columns"><Input label="Title" value={selected.title} onChange={e=>editArticle('title',e.target.value)}/><Input label="URL slug" value={selected.slug} onChange={e=>editArticle('slug',e.target.value)}/><Input label="Author" value={selected.author} onChange={e=>editArticle('author',e.target.value)}/><Input label="Date" type="date" value={selected.date} onChange={e=>editArticle('date',e.target.value)}/><Input label="Reading time" value={selected.readTime} onChange={e=>editArticle('readTime',e.target.value)}/><Input label="Local image path" value={selected.image} onChange={e=>editArticle('image',e.target.value)}/></div><Textarea label="Summary" value={selected.summary} onChange={e=>editArticle('summary',e.target.value)}/><Textarea label="Article body (simple HTML)" className="admin-code" value={selected.bodyHtml} onChange={e=>editArticle('bodyHtml',e.target.value)} hint="Supports p, h2, h3, ul, li, strong, em, a and blockquote."/><div className="admin-two-columns"><Input label="SEO title" value={selected.seoTitle} onChange={e=>editArticle('seoTitle',e.target.value)}/><Input label="SEO description" value={selected.seoDescription} onChange={e=>editArticle('seoDescription',e.target.value)}/></div><div className="admin-controls"><label className="admin-check"><input type="checkbox" checked={selected.draft} onChange={e=>editArticle('draft',e.target.checked)}/>Draft</label><label className="admin-check"><input type="checkbox" checked={selected.featured} onChange={e=>editArticle('featured',e.target.checked)}/>Featured article</label><a href={'/blog/'+selected.slug} target="_blank" rel="noreferrer">View article ↗</a><Button variant="danger" onClick={()=>{update(d=>{d.articles=d.articles.filter(a=>a.id!==articleId);});setArticleId('');}}>Remove article</Button></div><p className="admin-help">After saving, removed articles can be recovered from Revision history.</p></Card>}</>}
  {section==='translations'&&<><div className="admin-controls"><label>Language<select value={translationLocale} onChange={e=>setTranslationLocale(e.target.value)}><option value="fa">Persian</option><option value="ar">Arabic</option><option value="tr">Turkish</option></select></label><Input label="Search English source" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search a title or paragraph"/></div><p className="admin-help">English is the source language. New or edited English text appears here. Add its translation for each language, then save. Reset restores the bundled translation.</p><div className="admin-copy-list">{translationSources.map(source=><Card key={source}><p lang="en" dir="ltr">{source}</p><Textarea label="Translation" lang={translationLocale} dir={translationLocale==='tr'?'ltr':'rtl'} value={site.translations?.[translationLocale]?.[source]??payload.originals.translations[translationLocale]?.[source]??''} onChange={e=>update(d=>{d.translations??={};d.translations[translationLocale]??={};d.translations[translationLocale][source]=e.target.value;})}/><Button variant="ghost" size="sm" onClick={()=>update(d=>{delete d.translations?.[translationLocale]?.[source];})}>Reset translation</Button></Card>)}</div></>}
  {section==='design-system'&&<><div className="admin-design-tabs"><Tabs label="Design system views" items={[{id:'library',label:'Component library'},{id:'typography',label:'Typography'},{id:'tokens',label:'Design tokens'}]} value={designView} onChange={setDesignView}/></div><div role="tabpanel" aria-label={designView==='library'?'Component library':designView==='typography'?'Typography':'Design tokens'}>{designView==='library'?<DesignSystem embedded tokenOverrides={site.tokenOverrides} onEditTokens={()=>setDesignView('tokens')}/>:designView==='typography'?<><h2>Language fonts</h2><p>Choose separate fonts for Persian and Arabic. All options are hosted locally and apply to headings, body text and controls across the public website.</p><p className="admin-help">Preview your draft below, then Save changes to publish it. Reset restores the recommended font for that language. English and Turkish keep their existing typography.</p><LocaleTypography overrides={site.tokenOverrides} onChange={(key,value)=>update(d=>{if(value===null)delete d.tokenOverrides[key];else d.tokenOverrides[key]=value;})}/></>:<><p>Manage shared colors, fonts, spacing, radii and other style tokens. Preview your draft in Component library, then Save changes to apply it across the website.</p><p className="admin-help">Reset restores the original value. Changes remain in your draft until saved.</p><Input label="Search tokens" value={search} onChange={e=>setSearch(e.target.value)} placeholder="brand, font, space…"/>{Object.entries(payload.originals.tokens).map(([group,values])=>{const matching=Object.entries(values).filter(([name])=>(group+'-'+name).toLowerCase().includes(search.toLowerCase()));return matching.length>0&&<section key={group} className="admin-token-section"><h2 dir="ltr">{group}</h2><div className="admin-token-grid">{matching.map(([name,token])=>{const key=`--${group}-${name}`;return <div key={key}><Input label={key} value={site.tokenOverrides[key]??token.value} onChange={e=>update(d=>{d.tokenOverrides[key]=e.target.value;})}/><Button variant="ghost" size="sm" onClick={()=>update(d=>{delete d.tokenOverrides[key];})}>Reset</Button></div>;})}</div></section>;})}{!Object.entries(payload.originals.tokens).some(([group,values])=>Object.keys(values).some(name=>(group+'-'+name).toLowerCase().includes(search.toLowerCase())))&&<p>No tokens match your search.</p>}</>}</div></>}
  {section==='media'&&<><p>Original project images are local. Select an image and upload its replacement; the original file is preserved.</p><div className="admin-controls"><Input label="Search files" value={search} onChange={e=>setSearch(e.target.value)}/><label className="admin-upload">Upload image<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);try{const dataUrl=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});const result=await postJson('/api/admin/upload',{dataUrl});setUploaded(result.path);if(mediaTarget)update(d=>{d.assetOverrides[mediaTarget]=result.path;});setStatus('Image uploaded. Save changes to apply the replacement.');}catch(error){setStatus((error as Error).message);}finally{setBusy(false);}}}/></label></div>{uploaded&&<Input label="Uploaded image path for articles" value={uploaded} readOnly/>}{mediaTarget&&<p dir="ltr">Selected: {mediaTarget}<Button variant="ghost" onClick={()=>update(d=>{delete d.assetOverrides[mediaTarget];})}>Restore original image</Button></p>}<div className="admin-media-grid">{localImages.filter(a=>a.path.toLowerCase().includes(search.toLowerCase())).map(a=><button className={mediaTarget===a.path?'selected':''} key={a.path} onClick={()=>setMediaTarget(a.path)}><img src={site.assetOverrides[a.path]||a.path} alt={a.path.split('/').at(-1)} loading="lazy"/><small dir="ltr">{a.path.split('/').at(-1)}</small></button>)}</div></>}
  {section==='settings'&&<Card><div className="admin-two-columns"><Input label="Site name" value={site.settings.siteName} onChange={e=>update(d=>{d.settings.siteName=e.target.value;})}/><Input label="Footer text" value={site.settings.footerText} onChange={e=>update(d=>{d.settings.footerText=e.target.value;})}/><Input label="Dashboard label" value={site.settings.dashboardLabel} onChange={e=>update(d=>{d.settings.dashboardLabel=e.target.value;})}/><Input label="Dashboard URL" value={site.settings.dashboardUrl} onChange={e=>update(d=>{d.settings.dashboardUrl=e.target.value;})}/></div><h2>Navigation</h2>{site.settings.navigation.map((n,index)=><div className="admin-nav-row" key={index}><Input label="Title" value={n.label} onChange={e=>update(d=>{d.settings.navigation[index].label=e.target.value;})}/><Input label="URL" value={n.href} onChange={e=>update(d=>{d.settings.navigation[index].href=e.target.value;})}/><label className="admin-check"><input type="checkbox" checked={n.desktop} onChange={e=>update(d=>{d.settings.navigation[index].desktop=e.target.checked;})}/>Desktop</label><Button variant="ghost" onClick={()=>update(d=>{d.settings.navigation.splice(index,1);})}>Remove</Button><Button variant="ghost" disabled={!index} onClick={()=>update(d=>{const previous=d.settings.navigation[index-1];d.settings.navigation[index-1]=d.settings.navigation[index];d.settings.navigation[index]=previous;})}>↑</Button></div>)}<Button variant="secondary" onClick={()=>update(d=>{d.settings.navigation.push({label:'New link',href:'/',desktop:false});})}>Add navigation link</Button></Card>}
  {section==='submissions'&&<><div className="admin-controls"><h2>Contact messages ({payload.contacts.length})</h2><Button variant="secondary" onClick={()=>download('contacts.csv',csv(payload.contacts),'text/csv;charset=utf-8')}>Export CSV</Button></div><div className="admin-table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Message</th><th>Date</th></tr></thead><tbody>{payload.contacts.map(c=><tr key={c.id}><td>{c.name}</td><td dir="ltr">{c.email}</td><td>{c.message}</td><td dir="ltr">{c.created_at}</td></tr>)}</tbody></table></div><div className="admin-controls"><h2>Newsletter ({payload.subscribers.length})</h2><Button variant="secondary" onClick={()=>download('subscribers.csv',csv(payload.subscribers),'text/csv;charset=utf-8')}>Export CSV</Button></div><ul>{payload.subscribers.map(s=><li dir="ltr" key={s.email}>{s.email} — {s.created_at}</li>)}</ul></>}
  {section==='history'&&<><p>Each save preserves the previous version. Restoring a version also records a new revision.</p><Button variant="secondary" onClick={load}>Reload</Button><div className="admin-history">{payload.history.map(h=><Card key={h.id}><div><Badge tone="neutral">#{h.id}</Badge><p>{h.label}</p><small dir="ltr">{h.created_at}</small></div><Button variant="secondary" disabled={busy} onClick={()=>restore(h.id)}>Restore</Button></Card>)}</div>{!payload.history.length&&<p>No saved revisions yet.</p>}</>}
  </div></main>;
}
